### ISSUE TITLE
Misc key derivation changes

### ISSUE THREAD

**Issue by jtobin** [urbit/keygen-js#32]
From last week's email chain, we ought:

* Remove the optional 'password' salt throughout
* Remove the 'revision' salt throughout
* Not use the ship number to salt in childSeedFromSeed
* Fix all seeds at 256 bits
* Use an explicit out: 32 bytes argument to argon2
* Use an explicit derivation path of `m/44'/60'/0'/0/0`

See the updated wallet spec for details.

**Comment by Fang-** [comment]
idk if you're actively working on this rn, but I just pushed these changes. Made these before the weekend, but didn't push like an idiot. Hope this is still useful!

<img width="660" alt="image" src="https://user-images.githubusercontent.com/3829764/47311352-56ccdf80-d5ee-11e8-8f2f-b747e01fff4e.png">

**Comment by jtobin** [comment]
No sweat.  I don't mind duplicating work in the slightest -- work first, ask questions later. 😄

**Comment by jtobin** [comment]
(Just push em out and I'll merge/cut/etc. things appropriately).

**Comment by Fang-** [comment]
Alright, the new changelist, completely replacing the one in the issue OP, is as follows:

- [ ] Fix all seeds at 256 bits.
- [ ] Display seeds as BIP39 mnemonics rather than hex strings.
- [ ] Display BIP32 wallets as generated from the BIP39 mnemonic. That does a KDF that takes an optional password.
- [ ] Remove the optional 'password' salt, but do support inputting a password alongside the mnemonic.
- [ ] Rather than generating one ownership seed from a ticket, we need to be able to generate various ownership seeds from a ticket. This means that what we currently call the ownership seed needs to be salted and hashed, just like is done for the other seeds. Type here should be `'owner'`.

Yes, we *keep* the ship number and revision parts of the salt, but the UI will (at least initially) just default to `0` for both, as a default "Urbit-style derivation path". The UI will also default to "no password" for the mnemonics initially. Neither of these UI defaults are anything the lib needs to care about, but just fyi.

Wallet spec will be updated with this soon. @msutherl please double-check this changelist and ping here when the wallet spec has been updated.

**Comment by Fang-** [comment]
@msutherl we missed the BIP32 derivation path, which I've now added to the changelist.

**Comment by Fang-** [comment]
To clarify, are we doing BIP39 mnemonics also for networking seeds? Or just hex there?

**Comment by msutherl** [comment]
The hex is an intermediate representation that doesn't need to be exposed. BIP39 mnemonics are the output.
  
  
    
  
  
>

**Comment by Fang-** [comment]
But the networking seed is only relevant for Urbit itself, never goes into a hardware wallet or other Eth/Btc-related tech. Is Urbit going to do the mnemonic->seed conversion?

(This is fine, and I already have a lib for doing that, but I want to be explicit about whether we're doing that or not.)

**Comment by msutherl** [comment]
@msutherl woah, I totally misread that. Taking a second look at this, I'm starting to realize that the "networking seed" might be an accidental piece of cruft. Couldn't the Management Seed just as well be used to derive the networking keys?
